# Generated by Django 3.0.4 on 2020-04-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('associated_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_app.Profile')),
            ],
        ),
    ]
