# Generated by Django 3.0.4 on 2020-03-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_simpleaddpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleaddpicture',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
