# Generated by Django 3.0.4 on 2020-03-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_auto_20200315_0847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='simpleaddpicture',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
