# Generated by Django 3.0.4 on 2020-03-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0006_auto_20200315_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleaddpicture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
