# Generated by Django 3.0.4 on 2020-03-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0008_auto_20200317_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleaddpicture',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
